trainer_params.gradient_clipping:
  value: 1.0
trainer_params.optimizer_params.lr:
  value: 0.5
trainer_params.delta_scheduler_params.final_delta:
  value: 1.0
criterion_params.douce_delta:
  value: 0.01
