model_params.classifier_params.initial_variance:
  value: 1.0
seed:
  value: 65480
trainer_params.gradient_clipping:
  value: 0.1
trainer_params.optimizer_params.base_params.lr:
  value: 0.6721082233373061
trainer_params.variance_scheduler_params.min_variance:
  value: 0.0001
