model_params.classifier_params.initial_variance:
  value: 1.0
seed:
  value: 37878
trainer_params.gradient_clipping:
  value: 5.0
trainer_params.optimizer_params.base_params.lr:
  value: 0.9491899080869438
trainer_params.variance_scheduler_params.min_variance:
  value: 0.1
