model_params.classifier_params.initial_variance:
  value: 1000.0
seed:
  value: 26647
trainer_params.gradient_clipping:
  value: 10.0
trainer_params.variance_scheduler_params.min_variance:
  value: 1.0
