model_params:
  classifier_params:
    use_variance: true
    freeze_variance: true
    _hopt:
      initial_variance:
        distribution: log_uniform_values
        min: 1.0
        max: 1000.0
trainer_params:
  variance_scheduler_type: exponential
  variance_scheduler_params:
    _hopt:
      min_variance:
        distribution: log_uniform_values
        min: 0.0001
        max: 1.0
criterion_params:
  xent_weight: 0.0
  relaxed01_weight: 1.0
  relaxed01_type: poly
