trainer_params:
  delta_scheduler_type: exponential
  delta_scheduler_params:
    _hopt:
      final_delta:
        distribution: log_uniform_values
        min: 0.001
        max: 10.0
criterion_params:
  xent_weight: 0.0
  douce_weight: 1.0
  _hopt:
    douce_delta:
      distribution: log_uniform_values
      min: 0.001
      max: 10.0
    douce_smoothing:
      min: 0.0
      max: 0.2
